src/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView, LoginView
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),
    path('registration/', views.RegistrationView.as_view(template_name='accounts/registration.html'),
         name='registration'),
    path('settings/<int:pk>', views.SettingsView.as_view(), name='settings'),
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('retrospectives/', include('retrospectives.urls', namespace='retrospectives')),
    path('', include('retrospectives.urls', namespace='index')),
]

src/retrospectives/urls.py
from django.urls import path

from . import views

app_name = 'retrospectives'

urlpatterns = [
    path('<slug:slug>/', views.RetrospectiveDetailsView.as_view(), name='details'),
    path('<slug:slug>/add-values/', views.AddRetrospectiveNumberView.as_view(), name='add_values'),
    path('<int:pk>/update-values/', views.UpdateRetrospectiveNumberView.as_view(), name='update_values'),
    path('<int:pk>/feedback/', views.RetrospectiveUserFeedbackView.as_view(), name='feedback'),
    path('<int:feedback_pk>/<slug:slug>/vote/', views.vote, name='vote'),
    path('', views.IndexView.as_view(), name='index'),
]

src/main/templates/main/layout.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="{{ STATIC_URL }}Highcharts-6.1.3/highcharts.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap4/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/index.css">
    <title>Agile</title>
</head>
<body>

{% include 'main/navbar.html' %}

<div class="container">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% block content %}


    {% endblock %}
</div>

<script src="{{ STATIC_URL }}jquery/jquery-3.2.1.min.js"></script>
<script src="{{ STATIC_URL }}popper/popper.js"></script>
<script src="{{ STATIC_URL }}bootstrap4/js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}js/index.js"></script>
</body>
</html>

src/main/templates/main/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'retrospectives:index' %}">DCloud {% if team %}{{ team }}{% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item">
                <a class="nav-link {{ retrospectives_nav }}" href="{% url 'retrospectives:index' %}">Retrospectives</a>
            </li>
        </ul>

        <ul class="navbar-nav mr-right login">
            <li class="nav-item login-item">
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true" aria-expanded="false">{{ user|capfirst }}</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item {{ login_nav }}" href={% url 'accounts:logout' %}>Logout</a>
                        <a class="dropdown-item {{ settings_nav }}" href={% url 'accounts:settings' 1 %}>Settings</a>
                    </div>
                {% else %}
                    <a class="nav-link {{ login_nav }}" href={% url 'accounts:login' %}>Login</a>
                {% endif %}

                </li>
        </ul>


    </div>

</nav>