src/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('retrospectives/', include('retrospectives.urls', namespace='retrospectives')),
    path('', include('retrospectives.urls', namespace='index')),
]

src/retrospectives/urls.py
from django.urls import path

from . import views

app_name = 'retrospectives'

urlpatterns = [
    path('<slug:slug>/', views.RetrospectiveDetailsView.as_view(), name='details'),
    path('<slug:slug>/add-values/', views.AddRetrospectiveNumberView.as_view(), name='add_values'),
    path('<int:pk>/update-values/', views.UpdateRetrospectiveNumberView.as_view(), name='update_values'),
    path('<int:pk>/feedback/', views.RetrospectiveUserFeedbackView.as_view(), name='feedback'),
    path('<int:feedback_pk>/<slug:slug>/vote/', views.vote, name='vote'),
    path('', views.IndexView.as_view(), name='index'),
]

src/retrospectives/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver

from accounts.models import Team, AgileUser

FEEDBACK_TYPES = (('better', 'better'), ('great', 'great'))


class Retrospective(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    sprint_number = models.PositiveSmallIntegerField()
    slug = models.SlugField(blank=True)
    sprint_name = models.CharField(max_length=256)

    class Meta:
        unique_together = ('team', 'sprint_number',)

    def __str__(self):
        return str(self.sprint_number)


class RetrospectiveNumber(models.Model):
    sprint_number = models.ForeignKey(Retrospective, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    user = models.ForeignKey(AgileUser, on_delete=models.CASCADE)
    fun = models.PositiveSmallIntegerField()
    value = models.PositiveSmallIntegerField()
    great = models.CharField(max_length=512, blank=True, null=True)
    better = models.CharField(max_length=512, blank=True, null=True)

    def __str__(self):
        return str(self.sprint_number)


@receiver(pre_save, sender=Retrospective)
def save_profile(sender, instance, **kwargs):
    instance.slug = 'sprint-{}'.format(instance.sprint_number)


class RetrospectiveUserFeedback(models.Model):
    agile_user = models.ForeignKey(AgileUser, on_delete=models.CASCADE)
    retrospective_number = models.ForeignKey(RetrospectiveNumber, on_delete=models.CASCADE, related_name='feedback')
    text = models.CharField(max_length=512, blank=True, null=True)
    type = models.CharField(max_length=16, choices=FEEDBACK_TYPES)
    votes = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return self.text


class UserVote(models.Model):
    feedback = models.ForeignKey(RetrospectiveUserFeedback, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # TODO IS THIS CORRECT?
    voted = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=RetrospectiveUserFeedback)
def add_user_vote(sender, instance, **kwargs):
    user = User.objects.get(agile_user=instance.agile_user)
    UserVote.objects.update_or_create(
        feedback=instance, user=user,
        defaults={
            'user': user,
            'voted': True
        }
    )

src/retrospectives/forms.py
from django import forms

from retrospectives.models import RetrospectiveNumber, RetrospectiveUserFeedback

TEXT_WIDGET = {'cols': 20, 'rows': 5, 'class': 'form-control'}
SELECT_WIDGET = {'class': 'form-control'}


class AddRetrospectiveValuesForm(forms.ModelForm):
    # def clean(self):
    #     cleaned_data = super().clean()
    #     great = cleaned_data.get("great")
    #     if great is None:
    #         msg = 'Field is empty'
    #         self.add_error('great', msg)
    #
    #     better = cleaned_data.get("better")
    #     if better is None:
    #         msg = 'Field is empty'
    #         self.add_error('better', msg)

    class Meta:
        model = RetrospectiveNumber
        exclude = ('team', 'sprint_number', 'user', 'great', 'better')

        FUN_AND_VALUE_CHOICES = ((1, 'Terrible'), (2, 'Not so good'), (3, 'Good'), (4, 'Great'))


        widgets = {
            'fun': forms.Select(choices=FUN_AND_VALUE_CHOICES, attrs=SELECT_WIDGET),
            'value': forms.Select(choices=FUN_AND_VALUE_CHOICES, attrs=SELECT_WIDGET),
            # 'great': forms.Textarea(attrs=TEXT_WIDGET),
            # 'better': forms.Textarea(attrs=TEXT_WIDGET),
        }


class RetrospectiveUserFeedbackForm(forms.ModelForm):
    class Meta:
        model = RetrospectiveUserFeedback
        exclude = ('agile_user', 'retrospective_number', 'votes')

        labels = {
            'text': 'Feedback',
            'type': 'Great or better'
        }

        widgets = {
            'type': forms.Select(attrs=SELECT_WIDGET),
            'text': forms.Textarea(attrs=TEXT_WIDGET)
        }

src/retrospectives/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView, TemplateView, CreateView, UpdateView

from accounts.models import AgileUser
from retrospectives.forms import AddRetrospectiveValuesForm, RetrospectiveUserFeedbackForm
from retrospectives.models import Retrospective, RetrospectiveNumber, RetrospectiveUserFeedback, UserVote


def get_team(user):
    agile_user = AgileUser.objects.get(user=user)
    return agile_user.team


class IndexView(LoginRequiredMixin, ListView):
    model = Retrospective
    template_name = 'retrospectives/index.html'

    def get_context_data(self, **kwargs):
        retros = Retrospective.objects.filter(team=get_team(self.request.user)).order_by('sprint_number')

        # Building graph data
        agile_user = AgileUser.objects.get(user__username=self.request.user.username)
        graph_data = {}
        graph_values = []
        for retro in retros:
            data = retro.retrospectivenumber_set.all()
            fun = data.aggregate(Avg('fun'))
            value = data.aggregate(Avg('value'))
            graph_values.append({
                'fun': fun.get('fun__avg'),
                'value': value.get('value__avg'),
                'sprint_number': 'sprint {}'.format(retro.sprint_number)
            })
        graph_data['graph_values'] = graph_values
        graph_data['chart_type'] = agile_user.chart_type

        return {'retrospectives': retros.order_by('-sprint_number'), 'graph_data': graph_data,
                'page_tile': 'Retrospectives overview'}


class RetrospectiveDetailsView(LoginRequiredMixin, TemplateView):
    template_name = 'retrospectives/details.html'

    def __init__(self):
        self.slug = None
        self.team = None
        self.agile_user = None
        self.user = None
        self.sprint = None
        self.sprint_number = None
        self.retrospective_numbers = None
        self.details = None
        super(RetrospectiveDetailsView, self).__init__()

    def dispatch(self, request, *args, **kwargs):
        """
        Finding all values needed later for context
        """
        self.user = self.request.user
        self.agile_user = AgileUser.objects.get(user=self.user)
        self.team = get_team(self.request.user)
        self.slug = self.kwargs['slug']

        # If sprint does not exists redirect to retrospectives index
        try:
            self.sprint_number = Retrospective.objects.get(slug=self.slug, team=self.team)
        except Retrospective.DoesNotExist:
            messages.error(request, 'The sprint you wanted to goto does not exist.')
            return HttpResponseRedirect(reverse('retrospectives:index'))

        self.details = RetrospectiveNumber.objects.filter(team=self.team, sprint_number=self.sprint_number)

        self.retrospective_numbers = RetrospectiveNumber.objects.filter(team=self.team,
                                                                        sprint_number=self.sprint_number)

        # If user has not submitted feedback redirect to adding values
        if not self.retrospective_numbers:
            return HttpResponseRedirect(reverse('retrospectives:add_values', kwargs={'slug': self.slug}))

        return super(RetrospectiveDetailsView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):

        # Build a list of users who gave sprint feedback
        users = {}
        for user in self.retrospective_numbers:
            users[user.user] = user.user

        # Start building a feedback object which will be passed as context with feedback per user
        feedback_obj = []
        for user in users:
            user_feedback_list = []
            user_feedback = RetrospectiveUserFeedback.objects.filter(agile_user__team=self.team,
                                                                     agile_user=user,
                                                                     retrospective_number__sprint_number=self.sprint_number).order_by(
                '-votes')

            for feedback in user_feedback:
                user_feedback_list.append(
                    {'type': feedback.type, 'text': feedback.text, 'votes': feedback.votes, 'pk': feedback.pk,
                     'slug': self.slug}
                )

            feedback_obj.append({'user': user.user.username, 'feedback': user_feedback_list})

        # Build data for graph
        # retros = Retrospective.objects.filter(team=get_team(self.request.user)).order_by('-sprint_number')
        graph_data = {}
        graph_values = []
        for retro in self.details:
            graph_values.append(
                {
                    'user': retro.user.user.username,
                    'fun': retro.fun,
                    'value': retro.value,
                },
            )
        graph_data['graph_values'] = graph_values
        graph_data['chart_type'] = self.agile_user.chart_type

        return {
            'details': self.details, 'slug': self.slug, 'feedback_pk': self.sprint_number, 'graph_data': graph_data,
            'page_tile': 'Retrospective details ', 'sprint_name': self.sprint_number.sprint_name,
            'feedback_obj': feedback_obj
        }


class AddRetrospectiveNumberView(LoginRequiredMixin, CreateView):
    template_name = 'retrospectives/update_values.html'
    form_class = AddRetrospectiveValuesForm
    success_url = '/retrospectives/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

    def form_valid(self, form):
        user = self.request.user
        form.instance.team = get_team(user)
        form.instance.user = AgileUser.objects.get(user=user)
        form.instance.sprint_number = Retrospective.objects.get(team=get_team(self.request.user),
                                                                slug=self.kwargs['slug'])
        form.save()
        messages.success(self.request, 'Values saved')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'There was a problem submitting the form')
        return super().form_invalid(form)


class UpdateRetrospectiveNumberView(LoginRequiredMixin, UpdateView):
    form_class = AddRetrospectiveValuesForm
    template_name = 'retrospectives/update_values.html'
    model = RetrospectiveNumber

    def get_success_url(self):
        print(self.kwargs)
        retrospective_number_pk = self.kwargs.get('pk')
        retrospective = RetrospectiveNumber.objects.get(pk=retrospective_number_pk)
        sprint = Retrospective.objects.get(sprint_number=retrospective.sprint_number.sprint_number,
                                           team=get_team(self.request.user))
        return '/retrospectives/{}/'.format(sprint.slug)

    def get_context_data(self, **kwargs):
        context = super(UpdateRetrospectiveNumberView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        messages.success(self.request, 'Values updated')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'There was a problem submitting the form')
        return super().form_invalid(form)


def vote(request, feedback_pk, slug):
    # Checking if user already voted on this feedback
    feedback = RetrospectiveUserFeedback.objects.get(pk=feedback_pk)
    obj, created = UserVote.objects.update_or_create(
        feedback=feedback, user=request.user,
        defaults={
            'voted': True,
        }
    )
    # If user did not already voted, a combination user/feedback will be created in UserVote table hence created
    # will be True. If created is True the amount of votes for the feedback will be updated with plus one.
    if created:
        feedback.votes += 1
        feedback.save()
    else:
        messages.warning(request, 'You are the creator of this point or have already voted')
    return HttpResponseRedirect('/retrospectives/{}/'.format(slug))


class RetrospectiveUserFeedbackView(CreateView):
    form_class = RetrospectiveUserFeedbackForm
    success_url = '/retrospectives/feedback/'
    model = RetrospectiveUserFeedback
    template_name = 'retrospectives/feedback.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_success_url(self):
        retrospective_number = RetrospectiveNumber.objects.get(pk=self.kwargs.get('pk'))
        retrospective = Retrospective.objects.get(pk=retrospective_number.sprint_number.pk)
        return '/retrospectives/{}/'.format(retrospective.slug)

    def form_valid(self, form):
        feedback_pk = self.kwargs.get('pk')
        agile_user = AgileUser.objects.get(user__username=self.request.user.username)
        form.instance.agile_user = agile_user
        form.instance.retrospective_number = RetrospectiveNumber.objects.get(pk=feedback_pk)
        return super().form_valid(form)

src/retrospectives/templates/retrospectives/details.html
{% extends 'retrospectives/layout.html' %}

{% block retrospectives_content %}

    <div class="row">
        <div class="col-md-6">
            {% if not details %}
                <button class="btn btn-primary float-right"
                        onclick='location.href ="{% url 'retrospectives:add_values' slug %}"'>Add
                    retrospective values
                </button>

            {% else %}

                <button class="btn btn-warning float-right"
                        onclick='location.href ="{% url 'retrospectives:update_values' feedback_pk %}"'>Update values
                </button>
                <button class="btn btn-warning float-right"
                        onclick='location.href ="{% url 'retrospectives:feedback' feedback_pk %}"'>Add values
                </button>
            {% endif %}
        </div>
    </div>

    <div class="row details-content">
        <div class="col-md-6">
            <table class="table table-hover retro-details">
                <thead>
                <tr>
                    <th scope="col">Colleague</th>
                    <th scope="col">Sprint fun</th>
                    <th scope="col">Sprint value</th>
                </tr>
                </thead>
                <tbody>
                {% for values in details %}
                    <tr>
                        <td>{{ values.user|capfirst }}</td>
                        <td>{{ values.fun }}</td>
                        <td>{{ values.value }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <div class="col-md-6">
            {% include 'retrospectives/partials/details_chart.html' %}
        </div>

    </div>
    <div class="pb-2 mt-4 mb-2 border-bottom page-header">
        <h1>Colleague feedback</h1>
    </div>
    <div class="row user-values">


        {% for user_feedback in feedback_obj %}

            <div class="col-md">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{ user_feedback.user|capfirst }}</h5>
                        {% for feedback in user_feedback.feedback %}
                            {% if feedback.type == 'great' %}
                                <h6 class="card-subtitle great mb-2 text-muted">Great
                                    <span
                                            class="badge votes badge-secondary float-right"
                                            onclick='location.href ="{% url 'retrospectives:vote' feedback.pk slug%}"'>
                                        {{ feedback.votes }}
                                    </span>
                                </h6>
                                <p class="card-text">{{ feedback.text }}</p>
                            {% endif %}
                            {% if feedback.type == 'better' %}
                                <h6 class="card-subtitle better mb-2 text-muted">Better
                                    <span
                                            class="badge votes badge-secondary float-right"
                                            onclick='location.href ="{% url 'retrospectives:vote' feedback.pk slug%}"'>
                                        {{ feedback.votes }}
                                    </span>
                                </h6>
                                <p class="card-text">{{ feedback.text }}</p>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>

            </div>

        {% endfor %}


        {#        {% for feedback in details %}#}
        {#            <div class="col-md">#}
        {#                <div class="card" style="width: 18rem;">#}
        {#                    <div class="card-body">#}
        {#                        <h5 class="card-title">{{ feedback.user|capfirst }}</h5>#}
        {#                        {% if feedback.great %}#}
        {#                            <h6 class="card-subtitle great mb-2 text-muted">Great</h6>#}
        {#                            <p class="card-text">{{ feedback.great|linebreaksbr }}</p>#}
        {#                        {% endif %}#}
        {#                        {% if feedback.better %}#}
        {#                            <h6 class="card-subtitle better mb-2 text-muted">Better</h6>#}
        {#                            <p class="card-text">{{ feedback.better|linebreaksbr }}</p>#}
        {#                        {% endif %}#}
        {#                    </div>#}
        {#                </div>#}
        {##}
        {#            </div>#}
        {#        {% endfor %}#}
    </div>


{% endblock %}

src/retrospectives/templates/retrospectives/feedback.html
{% extends 'main/layout.html' %}

{% block content %}

    <h1>Add retrospective feedback</h1>
    <div class="row">
        <div class="col-md">
            <form method="POST" class="feedback-form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>







{% endblock %}

src/retrospectives/templates/retrospectives/feedback_backup.html
{% extends 'main/layout.html' %}

{% block content %}

    <h1>Add retrospective feedback</h1>
    <div class="row">
        <div class="col-md">
            <form method="POST" class="feedback-form">
                {% csrf_token %}

                {% for field in form %}
                    {% if field.name == 'text' %}
                        <div class="form-group">
                            <label for="{{ field.name }}">{{ field.name|capfirst }}</label>
                            <textarea class="form-control {{ field.name }} {% if field.errors %}input-error{% endif %}"
                                      id="{{ field.name }}"
                                      name="{{ field.name }}" rows="5">{{ field.value }}</textarea>
                        </div>
                    {% endif %}
                    {% if field.name == 'type' %}
                        <div class="form-group">
                            <label for="{{ field.name }}">Better or great</label>
                            <select class="form-control {{ field.name }}" id="{{ field.name }}" name={{ field.name }}>
                                {% for option in field %}
                                    {{ option }}
                                {% endfor %}
                            </select>
                        </div>
                    {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>







{% endblock %}

src/retrospectives/templates/retrospectives/index.html
{% extends 'retrospectives/layout.html' %}

{% block retrospectives_content %}



    <div class="row retrospectives-index">
        <div class="col-md">

            <table class="table table-hover retro-list">
                <thead>
                <tr>
                    <th scope="col">Sprint number</th>
                    <th scope="col">Sprint Name</th>
                </tr>
                </thead>
                <tbody>
                {% for retro in retrospectives %}
                    <tr onclick="window.document.location='{% url 'retrospectives:details' retro.slug %}';">
                        <td>{{ retro.sprint_number }}</td>
                        <td>{{ retro.sprint_name }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="col-md">
            {% include 'retrospectives/partials/index_chart.html' %}
        </div>
    </div>

{% endblock %}

src/retrospectives/templates/retrospectives/layout.html
{% extends 'main/layout.html' %}

{% block content %}
    <div class="pb-2 mt-4 mb-2 border-bottom page-header">
        <h1>{{ sprint_name }} <small></small></h1>
    </div>

    {% block retrospectives_content %}

    {% endblock %}

{% endblock %}

src/retrospectives/templates/retrospectives/update_values.html
{% extends 'main/layout.html' %}

{% block content %}

    <h1>Update retrospective numbers</h1>
    <div class="row">
        <div class="col-md">
            <form  method="POST">
                {% csrf_token %}
{#                {% include 'retrospectives/partials/update_values.html' %}#}

                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

{% endblock %}