src/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView, LoginView
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),
    path('registration/', views.RegistrationView.as_view(template_name='accounts/registration.html'),
         name='registration'),
    path('settings/<int:pk>', views.SettingsView.as_view(), name='settings'),
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('retrospectives/', include('retrospectives.urls', namespace='retrospectives')),
    path('', include('retrospectives.urls', namespace='index')),
]

src/accounts/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

CHART_CHOICES = (("column", "Column"), ("line", "Line"))


class Team(models.Model):
    team_name = models.CharField(max_length=128)

    def __str__(self):
        return self.team_name


class AgileUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='agile_user')
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    chart_type = models.CharField(max_length=16, default='column', choices=CHART_CHOICES)

    def __str__(self):
        return self.user.username

src/accounts/forms.py
from django import forms

from accounts.models import AgileUser, CHART_CHOICES


class AppSettingsForm(forms.ModelForm):
    class Meta:
        model = AgileUser
        exclude = ('team', 'user',)

        widgets = {
            'chart_type': forms.Select(choices=CHART_CHOICES),
        }

src/accounts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, CreateView, UpdateView

from accounts.forms import AppSettingsForm
from accounts.models import AgileUser


class LoginView(TemplateView):
    template_name = 'accounts/login.html'


class RegistrationView(LoginRequiredMixin, CreateView):
    success_url = reverse_lazy('accounts:login')
    model = User
    fields = ['username', 'password']

    def form_valid(self, form):
        data = form.cleaned_data
        self.save_user(data)
        return HttpResponseRedirect(reverse('accounts:login'))

    @staticmethod
    def save_user(data):
        User.objects.create(
            username=data.get('username'),
            password=data.get('password')
        )


class SettingsView(LoginRequiredMixin, UpdateView):
    form_class = AppSettingsForm
    template_name = 'accounts/settings.html'
    model = AgileUser

    def get_success_url(self):
        return '/accounts/settings/{}'.format(self.request.user.pk)

    def get_context_data(self, **kwargs):
        context = super(SettingsView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        messages.success(self.request, 'Values updated')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Settings could not be updated')
        return super().form_valid(form)

src/accounts/templates/accounts/login.html
{% extends 'main/layout.html' %}

{% block content %}

    <div id="login">
        <form class="form-horizontal" name="LoginForm" method="post">
            {% csrf_token %}
            {% if next %}
                <input type="hidden" name="next" value="{{ next }}"/>
            {% endif %}
            <div class="form-group">
                <label class="" for="username">Username</label>
                <div class="">
                    <input class="form-control" type="text" id="username" name="username" placeholder="Username">
                </div>
            </div>
            <div class="form-group">
                <label class="" for="password">Password</label>
                <div class="">
                    <input class="form-control" type="password" name="password" id="password" placeholder="Password">
                </div>
            </div>

            <button class="btn btn-primary" type="submit">Login</button>

        </form>

    <div class="loginRegistration">
        <a href={% url 'accounts:registration' %}>Register</a>
    </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/registration.html
{% extends 'main/layout.html' %}

{% block content %}
<h1>Registration</h1>

     <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>

{% endblock %}

src/accounts/templates/accounts/settings.html
{% extends 'main/layout.html' %}

{% block content %}

    <h1>Settings</h1>


    <div class="row">

        {# Django user settings #}
        <div class="col-md">
            <div class="table-responsive">
                <table class="table user-table">
                    <thead>
                    <tr>
                        <th colspan="2">User settings</th>

                    </tr>
                    </thead>
                    <tbody>

                    <tr>
                        <td>Username</td>
                        <td>{{ user.username }}</td>
                    </tr>
                    <tr>
                        <td>First name</td>
                        <td>{{ user.first_name|capfirst }}</td>
                    </tr>
                    <tr>
                        <td>Last name</td>
                        <td>{{ user.last_name }}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>{{ user.email }}</td>
                    </tr>


                    </tbody>
                </table>
            </div>
        </div>

        {# DCloud settings #}
        <div class="col-md">
            <div class="table-responsive">
                <table class="table user-table">
                    <thead>
                    <tr>
                        <th colspan="2">DCloud settings</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Team</td>
                        <td>{{ user.agile_user.team }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>

        </div>


        {# App settings #}
        <form method="POST">
            {% csrf_token %}

            <div class="col-md">
                <div class="table-responsive">
                    <table class="table user-table">
                        <thead>
                        <tr>
                            <th colspan="2">App settings</th>
                        </tr>
                        </thead>
                        <tbody>


                        {% for field in form %}
                            <tr>
                                <td><label for="{{ field.name }}">{{ field.label }}</label></td>

                                <td>
                                    <div class="form-group">

                                        <select class="form-control {{ field.name }}" id="{{ field.name }}"
                                                name="{{ field.name }}">
                                            {% for option in field %}
                                                {{ option }}
                                            {% endfor %}
                                        </select>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}


                        </tbody>
                    </table>

                </div>


            </div>

        <button type="submit" class="btn btn-primary">Submit</button>
        </form>


    </div>
{% endblock %}